### ISSUE TITLE
Adblock bloqueando imagem de patrocinadores

### ISSUE THREAD

**Issue by glaucocustodio** [braziljs/conf-boilerplate#119]
Pessoal, semelhante a issue https://github.com/braziljs/conf-boilerplate/issues/100, tive problemas com a classe `sponsor-logo` no chrome com a extensão Adblock Plus 1.8.12 e no firefox com a Adblock Plus 2.6.9.1-signed.

Esse é o tipo de problema que a gente se mata pra descobrir..

**Comment by larruda** [comment]
I'm facing the same issue here. Thank god @glaucocustodio reported this first, I was surely going to spend my night over it. Thanks my friend!

**Comment by zenorocha** [comment]
Pode mandar um PR @larruda?

**Comment by larruda** [comment]
Just created one: #125

**Comment by zenorocha** [comment]
🎉
