### ISSUE TITLE
Where is publish.sh?

### ISSUE THREAD

**Issue by rponte** [braziljs/conf-boilerplate#120]
Hi guys,

I'm not findind `publish.sh` on source code. README's project tells me to run it to publish to GithubPages.

Where is this file?

**Comment by larruda** [comment]
@rponte this file actually does not exist anymore because it's not necessary. Someone added a npm command to automatically deploy the site to GitHub Pages. You just need to run `npm run deploy` and it's done! I will open a PR to update the README text for this.

**Comment by zenorocha** [comment]
Exactly, see #124 for more info. Thanks @larruda!
