### ISSUE TITLE
Travis build is always failing for NodeJS version 0.8

### ISSUE THREAD

**Issue by larruda** [braziljs/conf-boilerplate#126]
Is it really necessary to build out at that version anymore? I can simply create a PR removing it so PR's stop failing unnecessarily.

**Comment by zenorocha** [comment]
Sure! Just added you as a collaborator, feel free to commit and push that change ;D

**Comment by larruda** [comment]
Thanks a lot @zenorocha !! ;D

**Comment by larruda** [comment]
This had just been fixed on commit 55b1fcb1d266f3fe2b6a4f06949966bcba099172 .

**Comment by zenorocha** [comment]
lol
