### ISSUE TITLE
Links to external resources should open in a new window/tab

### ISSUE THREAD

**Issue by larruda** [braziljs/conf-boilerplate#127]
As a matter of UI, links leading to external resources such as sponsor/partner website, event ticketing system, and also the links pointing to this GitHub repository (fork and footer) should all open their references in a new window/tab, thus preventing the user from leaving the conference/event website.

A simple `target="_blank"` on all existing anchors should fix this.

@zenorocha what's your thoughts on this?

**Comment by zenorocha** [comment]
SGTM 👍
