### ISSUE TITLE
Adicionar um botão de voltar ao topo no final da página.

### ISSUE THREAD

**Issue by felquis** [braziljs/conf-boilerplate#36]
Por conta da navegação no menu, senti falta de um link que me leve ao inicio de todo, como um "home" no menu, ou uma seta para cima no final da página... O que acham?

**Comment by pedropolisenso** [comment]
Não seria mais fácil e intuitivo fixar o menu e colocar um link Home?

**Comment by zenorocha** [comment]
We're working in a new default theme so this will no longer be a problem.
