### ISSUE TITLE
[Mobile] Descrição dos Speakers e descrição das Palestras

### ISSUE THREAD

**Issue by felquis** [braziljs/conf-boilerplate#44]
Seria interessante de na descrição dos speakers e na descrição da palestra, conteúdo que fica escondido na versão para mobile, ao tocar no conteúdo correspondente, ele aparecesse tipo um slidedown com o conteúdo, ou algo assim.. ai mesmo quem ta no mobile, conseguiria ter aquela informação(se tiver buscando por ela)

Uma coisas interessante seria fazer esse feature com uma animação que não cause reflows, só repaints, por que ficará muito lenta qualquer animação que cause reflows.

Aqui tem um print das partes que me refiro..

<img src="https://f.cloud.github.com/assets/736728/33395/86c77542-5084-11e2-9b87-35974768536f.png" width="250">

<img src="https://f.cloud.github.com/assets/736728/33396/89d8afc6-5084-11e2-925c-0bbf5ebee6df.png" width="250">

**Comment by zenorocha** [comment]
We're working in a new default theme so this will no longer be a problem.
