### ISSUE TITLE
[Mobile] Fazer todo o conteúdo como se fosse uma sanfona.

### ISSUE THREAD

**Issue by felquis** [braziljs/conf-boilerplate#45]
Não sei ao certo qual é o nome disso, "toggle content", "Sanfona" enfim.. na versão mobile, quando entrar no site, acredito que seria muito mais eficiente se todas as sessões de conteúdo, **about**, **Speakers**, **Location** etc... estivessem apenas o titulo e uma seta ao lado algo que indique que aquilo é clicável e quando a pessoa clica, expande o conteúdo(ou faça algo mais inteligência do que expandir) para mostrar o conteúdo daquela sessão..

Neste print eu simulei a ideia..
<img src="https://f.cloud.github.com/assets/736728/33423/04385dc0-508a-11e2-93fe-f4d6458c67da.png" width="250">

o que acham dessa melhoria?

**Comment by zenorocha** [comment]
We're working in a new default theme so this will no longer be a problem.
