### ISSUE TITLE
[Mobile] Top menu doesn't appear in resolution less than 481px

### ISSUE THREAD

**Issue by jaydson** [braziljs/conf-boilerplate#46]
I don't know if is a feature, but my suggestion is create another way to show the menus for users with resolution less than 481px.
A [Mashable](http://mashable.com/) approach is a good ideia.

![Screenshot from 2013-01-08 16:00:42](https://f.cloud.github.com/assets/72206/50995/6fd93662-59bd-11e2-9ba0-13be7490dc5e.png)

**Comment by zenorocha** [comment]
We're working in a new default theme so this will no longer be a problem.
