### ISSUE TITLE
Rethink new CB workflow

### ISSUE THREAD

**Issue by bernarddeluna** [braziljs/conf-boilerplate#81]
global
- mobileVersion: true, false;
- layout: static, fluid;
- googleFont: '';

header
- logo: img, text;

nav
- layout: static, fixed, scroll-fixed;

speakers
- order: schedule-time(default), az, za, id;
 - id: (pedro, paulo, plinio, portuga, pluto);
- hoster: true, false;
- keynote: true, false;
- lightningTalk: true, false;
- bio
 - id: 'pedro';
 - name
 - photo
 - desc
 - url
 - company
 - twitter
 - facebook
 - github
 - gplus
 - instagram

- schedule
 - slot
  - interval
    - yourClass
    - coffebreak
    - lunch
    - dinner
    - checkin*
    - open panel*
    - closing*
    - party*
    - keynote
    - lightning talk

sponsors
- sponsorGroup
 - desc: '';
 - label: 'Silver';
 - members
    - link
    - photo
    - name

partners
- partnerGroup
 - desc: '';
 - label: 'Silver';
 - members
    - link
    - photo
    - name

OBS: id e class para todas as entidades

**Comment by zenorocha** [comment]
Closing this one due to its inactivity.
