### ISSUE TITLE
Inconsistência no 'estilo' do código

### ISSUE THREAD

**Issue by felquis** [braziljs/conf-boilerplate#91]
Notei que no .editorcondig tem algumas configurações que não condizem com o que está nos arquivos, a maioria dos arquivos estão com tabs de 2 espaços, tanto HTML quanto JS, e configurações e .md

Seria o caso de padronizar tudo em 2 espaços, ou editar todos os arquivos para 4 espaços?

**Comment by zenorocha** [comment]
Closed at #114
