### ISSUE TITLE
Image path should be absolute in OG

### ISSUE THREAD

**Issue by leobaiano** [braziljs/conf-boilerplate#94]
Currently the image path in the OpenGraph code is relative and it generates an error on facebook, below print: 

![captura de tela de 2014-04-12 14 34 53](https://cloud.githubusercontent.com/assets/957257/2687719/501e405e-c269-11e3-8f99-11a1c1f955b8.png).

To fix the problem just enter the absolute path to the image, just point to the address of the web image (http://www.yoursite.com/badge.jpg).

![captura de tela de 2014-04-12 14 42 04](https://cloud.githubusercontent.com/assets/957257/2687726/f045192c-c269-11e3-8c1a-ed441395841e.png)

My suggestion to fix is ​​the inclusion of the code <%= @getUrl() %> at line 19 of file default.html.eco to bring the site URL defined in docpad.js and the function below at the end of docpad.js file to return the defined URL:

`
// Site Path
getUrl: function() {
    return this.site.url;
}
`

Line 19 of default.html.eco would be as follows: 

 <meta property="og:image" content="<%= @getUrl() %>/<%= @getTheme() %>/img/badge.jpg">

**Comment by gpedro** [comment]
this has been resolved. please, close this issue.

[default.html.eco#L19](https://github.com/gpedro/conf-boilerplate/blob/master/src/layouts/default.html.eco#L19)
